iPower_dir/offer_sections/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, TextAreaField, SubmitField

class ContactForm(FlaskForm):
  name = TextField("Name")
  last_name = TextField("Last Name")
  email = TextField("Email")
  subject = TextField("Subject")
  message = TextAreaField("Message")
  submit = SubmitField("Send")

iPower_dir/offer_sections/views.py
# project/offer_sections/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint, request, flash
from iPower_dir.models import Category
from iPower_dir.offer_sections.forms import ContactForm
from flask_mail import Message
from iPower_dir import app, mail

################
#### config ####
################

offer_sections_blueprint = Blueprint('offer_sections', __name__, template_folder='templates')


################
#### routes ####
################

@offer_sections_blueprint.route('/')
def index():
    all_categories = Category.query.all()
    return render_template('index.html', categories=all_categories)

@offer_sections_blueprint.route('/brands')
def brands():
    return render_template('brands.html')

@offer_sections_blueprint.route('/about')
def about():
    return render_template('about.html')

@offer_sections_blueprint.route('/construction')
def construction():
    all_categories = Category.query.filter_by(category_title="Construction")
    return render_template('products/products_construction.html', categories=all_categories)

@offer_sections_blueprint.route('/hardware')
def hardware():
    all_categories = Category.query.filter_by(category_title="Hardware")
    return render_template('products/products_hardware.html', categories=all_categories)

@offer_sections_blueprint.route('/agriculture')
def agriculture():
    all_categories = Category.query.filter_by(category_title="Agriculture")
    return render_template('products/products_agriculture.html', categories=all_categories)

@offer_sections_blueprint.route('/other')
def other():
    all_categories = Category.query.filter_by(category_title="Project & Other")
    return render_template('products/products_other.html', categories=all_categories)

@offer_sections_blueprint.route('/contacts', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':
            msg = Message(form.subject.data, sender='info@ipowerindustry.com', recipients=['info@ipowerindustry.com'])
            msg.body = """
            This message is send from ipowerindustry.com home page.
            From: %s %s <%s>
            Message: %s
            """ % (form.name.data, form.last_name.data, form.email.data, form.message.data)
            mail.send(msg)
            app.logger.warning('Email send')
            return render_template('contact.html', success=True)

    elif request.method == 'GET':
        app.logger.warning('Showing contact page')
        return render_template('contact.html', form=form)

iPower_dir/offer_sections/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About I-Power
{% endblock %}

{% block body %}
        <section id="inner-headline">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="breadcrumb">
							<li><a href="#"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
							<li><a href="#">About Us</a><i class="icon-angle-right"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

<section id="content">
			<div class="container">

				<!-- Descriptions -->
				<div class="row">
					<div class="col-lg-12">
                        <img src="../../static/img/about_img.jpg" alt="" class="align-right" width="50%" />
                        <!-- Description -->
						<h4>About I-Power Industry & Trade Co. Ltd</h4>
						<dl>
							<dt>OVERVIEW</dt>
							<dd>
                                        I-Power Industry and Trade is a specialized trading company of architectural
                                and building materials that connects housing material manufacturers with users such as building
                                material wholesalers and house constructors. We are a “multi-functional specialized trading company”
                                responsible for the sale of various housing materials, the development of product and distribution
                                channels for housing materials, the supply of housing parts/components both inside and outside of Rwanda,
                                and working with related building construction contracts. As a company that can respond to various needs
                                ranging from the procurement of materials to processing and sales, we are expanding the reach of our
                                business in not only the field of new housing and apartment interiors, but also in the reform and
                                non-housing fields.
                            </dd>

							<dt>EXPERIENCE</dt>
							<dd>
                                In addition to our expertise in our product lines, manufacturing and trading, our group
                                enjoys over 15 collective years of technical, advisory and
                                support experience and  also the company had tie up over 20 international companies
                                who are prominent suppliers of various products throughout the world.
                            </dd>
							<dt>OUR SUPPLIERS</dt>
							<dd>
                                We now offer our services on a project to project,
                                or a long term contractual basis to both large and small developers throughout  Rwanda and
                                specifically within Kigali.
                                Our suppliers share and provide us with a value added experience, where they in turn and on a
                                continuous basis append us with their latest norms, product features and usage. Our suppliers
                                follow up with worldwide product distribution, installation and maintenance and create an infinite
                                network of knowledge among all retailers.
                            </dd>
						</dl>
					</div>

				</div>
			</div>
		</section>
{% endblock %}

iPower_dir/offer_sections/templates/brands.html
{% extends 'layout.html' %}

{% block title %}
    Brands
{% endblock %}

{% block body %}

<section id="inner-headline">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="breadcrumb">
							<li><a href="#"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
							<li><a href="#">Our Brands</a><i class="icon-angle-right"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

    <div class="text-center" style="margin-top: 30px; margin-bottom: 30px">
        <img class="brands_img" src="{{ url_for('static', filename='img/brands.jpg') }}">
    </div>

{% endblock %}

iPower_dir/offer_sections/templates/categories.html
{% extends 'layout.html' %}

{% block title %}
    Categories
{% endblock %}

{% block body %}

    <table style="width:100%">
      <tr>
        <td>Title</td>
        <td>Description</td>
      </tr>
      {% for category in categories %}
          <tr>
            <td>{{ category.category_title }}</td>
            <td>{{ category.category_description }}</td>
          </tr>
          <tr>
              {% for item in category.items %}
                  <td>{{ item.name }}</td>
                  {% for picture in item.pictures %}
                    <td>{{ picture.picture_name }}</td>
                  {% endfor %}
              {% endfor %}
          </tr>
      {% endfor %}
    </table>
{% endblock %}




iPower_dir/offer_sections/templates/contact.html
{% extends 'layout.html' %}

{% block title %}
    Contacts
{% endblock %}

{% block body %}

    <section id="inner-headline">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="breadcrumb">
							<li><a href="#"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
							<li><a href="#">Contact Us</a><i class="icon-angle-right"></i></li>
						</ul>
					</div>
				</div>
			</div>
		</section>

    {% if message %}
        {{ message }}
    {% endif %}
    {% if success %}
       <div class="alert alert-success">
          <strong>Thank you for your message.</strong> We will get back to you shortly.
        </div>
     {% endif %}

<section id="content">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
                            <h4>We are here for you</h4>
                            <img src="../../static/img/contact_img.jpg" alt="" class="align-right" width="40%"/>
                            <dl class="dl-horizontal">
                                <dt>BUY</dt>
                                <dd>You can start buying goods from our provided products by clicking contact button,
                                        filling the right information in the form and sending us your request.</dd>
                                <br>
                                <dt>SELL</dt>
                                <dd>If you have goods that you want us to sell - click contact button,
                                        fill in the right information in the form and send us your proposal. We would review it and get back to you.
                                    </dd>
                            </dl>

                        <!-- divider -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="solidline">
                                </div>
                            </div>
                        </div>
                        <!-- end divider -->
						<h4>Get in touch with us by filling <strong>contact form below</strong></h4>
                        <form action="{{ url_for('offer_sections.contact') }}" method="post" role="form" class="contactForm">
							<div class="form-group">
								<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validation"></div>
							</div>
							<div class="form-group">
								<input type="text" name="last_name" class="form-control" placeholder="Your Last Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validation"></div>
							</div>
							<div class="form-group">
								<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
								<div class="validation"></div>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
								<div class="validation"></div>
							</div>
							<div class="form-group">
								<textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
								<div class="validation"></div>
							</div>

							<div class="text-center"><button type="submit" class="btn btn-theme">Send Message</button></div>
						</form>
					</div>
				</div>
			</div>
		</section>

{% endblock %}

iPower_dir/offer_sections/templates/includes/_footer.html
<!-- footer -->


<footer>
			<div class="container">
				<div class="row">
					<div class="col-lg-3">
						<div class="widget">
							<h5 class="widgetheading">Get in touch with us</h5>
							<address>
					<strong>I-Power Industry & Trade Co. Ltd</strong><br>
					 Umukindo Center / Gisozi, Gakinjiro<br>
                                Kigali, Rwanda
					  </address>
							<p>
								<i class="icon-phone"></i>(250) 73 22 43 000 - (250) 78 22 43 000<br>
								<i class="icon-envelope-alt"></i> info@ipowerindustry.com
							</p>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="widget">
							<h5 class="widgetheading">Pages</h5>
							<ul class="link-list">
                                <li><a href="about">About Us</a></li>
                                <li><a href="brands">Our Partners</a></li>
                                <li><a href="contacts">Contact Us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="widget">
							<h5 class="widgetheading">We offer</h5>
							<ul class="link-list">
                                <li><a href="construction">Construction services</a></li>
                                <li><a href="hardware">Hardware tools</a></li>
                                <li><a href="agriculture">Agriculture equipment</a></li>
                                <li><a href="other">Everything required for your project</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="widget">
							<h5 class="widgetheading">Products's Photostream</h5>
							<div class="flickr_badge">
								<script type="text/javascript" src="https://www.flickr.com/badge_code_v2.gne?count=8&amp;display=random&amp;size=s&amp;layout=x&amp;source=user&amp;user=156123970@N02"></script>
							</div>
							<div class="clear">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="sub-footer">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="copyright">
								<p>&copy; I-Power Industry & Trade Co. Ltd. All right reserved.</p>
								<div class="credits">
									Frontend and backend by <a href="https://leiko.me/">Ilja Leiko</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
<!-- //footer -->

iPower_dir/offer_sections/templates/includes/_header.html
	<div class="header" id="home">
		<div class="container">
			<div>
                <a href="/"><img class="w3l_logo" src="{{ url_for('static', filename='img/logo.png') }}" width="80%"></a>
            </div>
            <div class="clearfix"> </div>
		</div>
	</div>

iPower_dir/offer_sections/templates/includes/_navbar.html
<header>
			<div class="navbar navbar-default navbar-static-top">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                        <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename='img/logo.png') }}" height="100px"></a>
					</div>
					<div class="navbar-collapse collapse ">
						<ul class="nav navbar-nav">
							<li><a href="/">Home</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Our Products <b class=" icon-angle-down"></b></a>
								<ul class="dropdown-menu">
									<li><a href="construction">Construction</a></li>
									<li><a href="hardware">Hardware</a></li>
									<li><a href="agriculture">Agriculture</a></li>
                                    <li><a href="other">Project & Other</a></li>
								</ul>
							</li>
							<li><a href="brands">Brands</a></li>
							<li><a href="about">About Us</a></li>
							<li><a href="contacts">Contacts</a></li>
						</ul>
					</div>
				</div>
			</div>

</header>



iPower_dir/offer_sections/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    I-Power
{% endblock %}

{% block body %}
		<section id="featured">
			<!-- start slider -->
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<!-- Slider -->
						<div id="main-slider" class="flexslider">
							<ul class="slides">
								<li>
									<img src="{{ url_for('static', filename='img/carousel_1.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Doors</h3>
										<p>We produce high quality doors you will like!</p>
										<a href="{{ url_for('static', filename='catalogs/Doors.pdf') }}" target="_blank" class="btn btn-theme">Learn More</a>
									</div>
								</li>
								<li>
									<img src="{{ url_for('static', filename='img/carousel_2.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Balconies</h3>
										<p>Adding value to your property</p>
										<a href="construction" class="btn btn-theme">Learn More</a>
									</div>
								</li>
								<li>
									<img src="{{ url_for('static', filename='img/carousel_3.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Aluminum & PVC Works</h3>
										<p>We produce aluminum doors, windows, bath doors, p.v.c. paneling, celling and so much more!</p>
										<a href="{{ url_for('static', filename='catalogs/Kamaka.pdf') }}" target="_blank" class="btn btn-theme">Learn More</a>
									</div>
								</li>
								<li>
									<img src="{{ url_for('static', filename='img/carousel_4.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Handrails & Staircases</h3>
										<p>A luxury staircase in the foyer can be quite the centerpiece in any home and can accentuate the overall home decor..</p>
										<a href="construction" class="btn btn-theme">Learn More</a>
									</div>
								</li>
								<li>
									<img src="{{ url_for('static', filename='img/carousel_5.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Generators & Solar Heaters</h3>
										<p>Demand for solar power is rapidly heating up. We provide all sorts of generators and solar heaters.</p>
										<a href="{{ url_for('static', filename='catalogs/Diesel_generators.pdf') }}" target="_blank" class="btn btn-theme">Learn More</a>
									</div>
								</li>
								<li>
									<img src="{{ url_for('static', filename='img/carousel_6.jpg') }}" alt="" />
									<div class="flex-caption">
										<h3>Iron Works</h3>
										<p>From custom designs to sports memorabilia, sturdy signs to elegant decor,
                                            we strive to bring you the highest quality of product available.</p>
										<a href="construction" class="btn btn-theme">Learn More</a>
									</div>
								</li>
							</ul>
						</div>
						<!-- end slider -->
					</div>
				</div>
			</div>
		</section>


		<section class="callaction">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="big-cta">
							<div class="cta-text">
                                <h2>Welcome To <span>I-Power Industry & Trade Co. Ltd</span></h2>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

        <section id="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="row">
							<div class="col-lg-3">
								<div class="box">
									<div class="box-gray aligncenter">
										<h4>Out catalogs</h4>
										<div class="icon">
											<i class="fa fa-file fa-3x"></i>
										</div>

                                        <ul class="catalog">
                                            <li><a href="{{ url_for('static', filename='catalogs/Diesel_generators.pdf') }}" target="_blank">Diesel generators</a></li>
                                            <li><a href="{{ url_for('static', filename='catalogs/Doors.pdf') }}" target="_blank">Doors</a></li>
                                            <li>Catalog <a href="{{ url_for('static', filename='catalogs/Kamaka.pdf') }}" target="_blank">One</a> &
                                                <a href="{{ url_for('static', filename='catalogs/Catalog_2.pdf') }}" target="_blank">Two</a></li>
                                        </ul>

									</div>
									<div class="box-bottom">
										<a>Choose the catalog</a>
									</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="box">
									<div class="box-gray aligncenter">
										<h4>Our Products</h4>
										<div class="icon">
											<i class="fa fa-industry fa-3x"></i>
										</div>
										<p>
											See our groundbreaking products,
                                            designed to help you achieve more!
										</p>

									</div>
									<div class="box-bottom">
										<a>See navigation bar</a>
									</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="box">
									<div class="box-gray aligncenter">
										<h4>Our Partners</h4>
										<div class="icon">
											<i class="fa fa-briefcase fa-3x"></i>
										</div>
										<p>
											Proud to have partners and strategic
                                            alliances to deliver award-winning products and services.
										</p>

									</div>
									<div class="box-bottom">
										<a href="brands">Click to learn more</a>
									</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="box">
									<div class="box-gray aligncenter">
										<h4>Contact Us</h4>
										<div class="icon">
											<i class="fa fa-envelope-open fa-3x"></i>
										</div>
										<p>
											Have any questions?
                                            Please fill the form to contact us and we'll respond promptly.
										</p>

									</div>
									<div class="box-bottom">
										<a href="contacts">Send us an email</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- divider -->
				<div class="row">
					<div class="col-lg-12">
						<div class="solidline">
						</div>
					</div>
				</div>
				<!-- end divider -->
			</div>
		</section>

{% endblock %}

iPower_dir/offer_sections/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Construction, industry, doors" />

    <!-- For mobile apps - hide URL bar -->
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); }
    </script>

    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" media="all" />
	<link href="{{ url_for('static', filename='css/fancybox/jquery.fancybox.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/jcarousel.css') }}" rel="stylesheet" />
	<link href="{{ url_for('static', filename='css/flexslider.css') }}" rel="stylesheet" />
	<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mansory.css') }}" />

	<!-- Theme skin -->
	<link href="{{ url_for('static', filename='css/default.css') }}" rel="stylesheet" />

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Glegoo:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yrsa" rel="stylesheet">
</head>
<body>
    <div id="wrapper">
        {% include 'includes/_navbar.html' %}

        {% block body %}{% endblock %}

        {% include 'includes/_footer.html' %}
    </div>


    <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
    <!-- Javascripts -->


	<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.fancybox.pack.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.fancybox-media.js') }}"></script>
	<script src="{{ url_for('static', filename='js/google-code-prettify/prettify.js') }}"></script>
	<script src="{{ url_for('static', filename='js/portfolio/jquery.quicksand.js') }}"></script>
	<script src="{{ url_for('static', filename='js/portfolio/setting.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.flexslider.js') }}"></script>
	<script src="{{ url_for('static', filename='js/animate.js') }}"></script>
	<script src="{{ url_for('static', filename='js/custom.js') }}"></script>

    <script src="{{ url_for('static', filename='js/masonry.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/mansory.js') }}"></script>





</body>
</html>

iPower_dir/offer_sections/templates/products/products_agriculture.html
{% extends 'layout.html' %}

{% block title %}
    Agriculture
{% endblock %}

{% block body %}

<section id="inner-headline">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="breadcrumb">
							<li><a href="#"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
							<li><a href="#">Our Products</a><i class="icon-angle-right"></i></li>
							<li class="active">Agriculture</li>
						</ul>
					</div>
				</div>
			</div>
		</section>

<section id="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<h4>
                            {% for category in categories %}
                                {{ category.category_description }}
                            {% endfor %}
                        </h4>
					</div>
				</div>
				<!-- divider -->
				<div class="row">
					<div class="col-lg-12">
						<div class="solidline">
						</div>
					</div>
				</div>
				<!-- end divider -->
                <div id="grid">
                    <div id="posts">
                        {% for category in categories %}
                            {% for item in category.items %}
                                <div class="post" id="{{ item.href }}">
                                    <!--TODO find a way to provide more universal image src -->
                                    <img alt="{{ item.name }}" style="width: 100%" src="../../../static/img/products/{{ item.picture_uri }}">
                                    <br>
                                    <p style="font-size: large"><strong>{{ item.name }}</strong></p><br>
                                    <p><small>{{ item.description }}</small></p>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    </div>
                </div>
			</div>
		</section>


{% endblock %}

iPower_dir/offer_sections/templates/products/products_construction.html
{% extends 'layout.html' %}

{% block title %}
    Construction
{% endblock %}

{% block body %}

<section id="inner-headline">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<ul class="breadcrumb">
							<li><a href="#"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
							<li><a href="#">Our Products</a><i class="icon-angle-right"></i></li>
							<li class="active">Construction</li>
						</ul>
					</div>
				</div>
			</div>
		</section>

<section id="content">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<h4>
                            {% for category in categories %}
                                {{ category.category_description }}
                            {% endfor %}
                        </h4>
					</div>
				</div>
				<!-- divider -->
				<div class="row">
					<div class="col-lg-12">
						<div class="solidline">
						</div>
					</div>
				</div>
				<!-- end divider -->
                <div id="grid">
                    <div id="posts">
                        {% for category in categories %}
                            {% for item in category.items %}
                                <div class="post" id="{{ item.href }}">
                                    <!--TODO find a way to provide more universal image src -->
                                    <img alt="{{ item.name }}" style="width: 100%" src="../../../static/img/products/{{ item.picture_uri }}">
                                    <br>
                                    <p style="font-size: large"><strong>{{ item.name }}</strong></p><br>
                                    <p><small>{{ item.description }}</small></p>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    </div>
                </div>
			</div>
		</section>




{% endblock %}